[package]
name = "telegram-bot"
version = "0.1.0"
authors = ["Maxim Schepelin <m.schepelin@gmail.com>"]

[dependencies]
mockito = "0.9.0"
reqwest = "0.8.*"
serde = "1.0.*"
serde_json = "1.0.*"
serde_derive = "1.0.*"
